apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../apps

images:
  - name: ghcr.io/nduka45/cashmate-api-gateway
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-credit-service
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-customer-service
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-loan-service
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-payment-service
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-notification-service
    newTag: v1
  - name: ghcr.io/nduka45/cashmate-disbursement-service
    newTag: v1