apiVersion: v1
kind: ConfigMap
metadata:
  name: cashmate-config
  namespace: cashmate
data:
  NODE_ENV: "development"
  PORT: "3000"

  # PostgreSQL
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cashmate"

  # Kafka
  KAFKA_BROKER: "cashmate-kafka-service:9092"