apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: cashmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: cashmate-loan-service:1.1
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: NODE_ENV

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: DB_NAME

            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: cashmate-config
                  key: KAFKA_BROKER

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cashmate-secrets
                  key: JWT_SECRET

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cashmate-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashmate-secrets
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: cashmate
spec:
  selector:
    app: loan-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP