services:
  postgres:
    image: postgres:16-alpine
    container_name: cashmate-postgres
    environment:
      POSTGRES_DB: cashmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cashmate_postgres_data:/var/lib/postgresql/data
      - ../../loan-service/src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  kafka:
    image: apache/kafka:3.7.0
    container_name: cashmate-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  loan-service:
    build:
      context: ../../loan-service
      dockerfile: Dockerfile
    container_name: cashmate-loan-service
    environment:
      PORT: 3000
      NODE_ENV: development
      JWT_SECRET: cashmate-dev-secret
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cashmate
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BROKER: kafka:9092
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - kafka

volumes:
  cashmate_postgres_data: