apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service
  namespace: cashmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-service
  template:
    metadata:
      labels:
        app: credit-service
    spec:
      containers:
        - name: credit-service
          image: ghcr.io/nduka45/cashmate-credit-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "cashmate"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cashmate-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashmate-secret
                  key: DB_PASSWORD
            - name: KAFKA_BROKER
              value: "kafka:9092"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: credit-service
  namespace: cashmate
spec:
  selector:
    app: credit-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP