apiVersion: v1
kind: Service
metadata:
  name: disbursement-service
  namespace: cashmate
spec:
  selector:
    app: disbursement-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP