apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - customer-service.yaml
  - loan-service.yaml
  - loan-service-hpa.yaml
  - credit-service.yaml
  - disbursement-service.yaml
  - payment-service.yaml
  - notification-service.yaml
