apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cashmate

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: ghcr.io/nduka45/cashmate-notification-service:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3006

          env:
            - name: PORT
              value: "3006"
            - name: KAFKA_BROKER
              value: "kafka:9092"

          startupProbe:
            httpGet:
              path: /health
              port: 3006
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 10
            periodSeconds: 10

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"